### PR TITLE
Refactor PredictCommand

### PR DESCRIPTION
**Pull request by kwmsmith**
The previous version used class-level attributes for arguments; this
refactoring uses instance-level attributes.

NOTE: Untested!

### CODE REVIEW

**Comment by kwmsmith** [comment]
@BrentDorsey @cfregly

**Comment by cfregly** [comment]
@kwmsmith this is glorious!  __init__ and *kwargs are both mysterious and awesome at the same time.

btw, how do you know which imports are unused?  in JVM land, my IDE usually highlights the unused imports.  what do you use?  or do you just eye-ball it?

**Comment by kwmsmith** [comment]
I use a python linting utility called `flake8` that's integrated into my editor -- it highlights unused imports and I have a hard time not deleting them :)

http://flake8.pycqa.org/en/latest/

**Comment by BrentDorsey** [comment]
Which python editor do you use?  I’m betting it’s not Intellij ☺

**Comment by kwmsmith** [comment]
> Which python editor do you use?  I’m betting it’s not Intellij ☺

I'm a lifelong vim user with a few dozen extensions to make it more like an IDE.  hjkl FTW!

**Pull request merged**
