### PR TITLE
pbm with nohup/amp; in last spark notebook, using screen instead

### PR DESCRIPTION
**Pull request by andypetrella**
So this adds screen to the mix  because 0.6.0 uses SBT to download dependency and this doesn't behave well in background mode :-[

**VERY IMPORTANT**
The current spark notebook distro is outdated (probably a pre-release on the master):
So https://s3.amazonaws.com/fluxcapacitor.com/packages/spark-notebook-0.6.0-scala-2.10.4-spark-1.4.1-hadoop-2.6.0-with-hive-with-parquet.tgz
should be replaced by this
https://s3.eu-central-1.amazonaws.com/spark-notebook/tgz/spark-notebook-0.6.0-scala-2.10.4-spark-1.4.1-hadoop-2.6.0-with-hive-with-parquet.tgz

### CODE REVIEW

**Comment by andypetrella** [comment]
Sad point, this changes the Dockerfile, hence the 2G will have to be DL again :'(

**Comment by cfregly** [comment]
thanks, @andypetrella !

**Comment by andypetrella** [comment]
no problemo @cfregly , did you also uploaded the right tgz on s3?

**Comment by cfregly** [comment]
just uploaded the new version.

thanks @andypetrella

**Comment by andypetrella** [comment]
we need to pull the docker images again then?

On Mon, Aug 3, 2015 at 8:03 PM Chris Fregly <notifications@github.com>
wrote:

> just uploaded the new version.
>
> thanks @andypetrella <https://github.com/andypetrella>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fluxcapacitor/pipeline/pull/3#issuecomment-127353836>.
>
-- 
andy

**Pull request merged**
